CREATE TABLE posts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    likes INT NOT NULL DEFAULT 0,
    content TEXT NOT NULL,
    removed BOOL NOT NULL DEFAULT FALSE,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

